"""CLI: python -m neura_runtime --port 0 --token <token> --workspace <path>.

The IPython executor owns the main thread; uvicorn runs in a separate thread.
Stdout is reserved for a single readiness handshake. Server diagnostics go to
stderr, and the token is never included in the handshake or logs.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import socket
import sys
import threading
from pathlib import Path

import uvicorn

from neura_core.api import API_VERSION
from neura_runtime.executor import Executor
from neura_runtime.server import create_app

STARTUP_TIMEOUT_S = 15.0


class _RuntimeServer(uvicorn.Server):
    def __init__(self, config: uvicorn.Config) -> None:
        super().__init__(config)
        self.startup_finished = threading.Event()

    async def startup(self, sockets=None) -> None:
        await super().startup(sockets=sockets)
        # Uvicorn has finished lifespan startup and is accepting connections.
        # Printing before this point would race the extension's first request.
        self.startup_finished.set()


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Neura managed, localhost-only Python runtime")
    parser.add_argument("--port", type=int, default=0, help="loopback port; 0 selects a free port")
    parser.add_argument("--token", required=True, help="Bearer token generated by the extension")
    parser.add_argument("--workspace", required=True, type=Path, help="workspace directory")
    args = parser.parse_args(argv)
    if not 0 <= args.port <= 65535:
        parser.error("--port must be between 0 and 65535")
    if not args.token.strip():
        parser.error("--token must not be empty")
    args.workspace = args.workspace.resolve()
    if not args.workspace.is_dir():
        parser.error("--workspace must be an existing directory")
    return args


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    executor = None
    server = None
    server_thread = None
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        try:
            # Keep the actual port-0 socket: no close-and-rebind race, and no
            # host override that could accidentally expose user-code execution.
            listener.bind(("127.0.0.1", args.port))
            port = listener.getsockname()[1]
            os.chdir(args.workspace)
            sys.path.insert(0, str(args.workspace))
            with contextlib.redirect_stdout(sys.stderr):
                executor = Executor(str(args.workspace))
            server = _RuntimeServer(
                uvicorn.Config(
                    create_app(args.token, executor),
                    host="127.0.0.1",
                    port=port,
                    access_log=False,
                    log_level="warning",
                    loop="asyncio",
                    proxy_headers=False,
                    timeout_graceful_shutdown=3,
                )
            )
            server_errors: list[BaseException] = []

            def serve() -> None:
                try:
                    server.run(sockets=[listener])
                except BaseException as exc:
                    server_errors.append(exc)
                finally:
                    server.startup_finished.set()  # also wake main on failure
                    executor.shutdown()

            server_thread = threading.Thread(target=serve, name="neura-http", daemon=True)
            server_thread.start()
            if not server.startup_finished.wait(STARTUP_TIMEOUT_S):
                raise RuntimeError("HTTP server startup timed out")
            if not server.started:
                raise RuntimeError("HTTP server failed to start")
            print(
                json.dumps(
                    {
                        "neura_runtime": True,
                        "port": port,
                        "pid": os.getpid(),
                        "version": API_VERSION,
                    }
                ),
                flush=True,
            )
            executor.run_forever()
            if server_errors:
                raise RuntimeError("HTTP server stopped unexpectedly")
            return 0
        except (OSError, RuntimeError) as exc:
            print(f"neura_runtime: {exc}", file=sys.stderr, flush=True)
            return 1
        finally:
            if server is not None:
                server.should_exit = True
            if executor is not None:
                executor.shutdown()
            if server_thread is not None:
                server_thread.join(timeout=5)
            if executor is not None:
                executor.close()


if __name__ == "__main__":
    raise SystemExit(main())
